general:
  proxy:
    http: 'http://127.0.0.1:your_port' # TODO: set your proxy
    https: 'http://127.0.0.1:your_port' # TODO: set your proxy
    ftp: 'ftp://127.0.0.1:your_port' # TODO: set your proxy
    host: 'http://localhost:your_port' # TODO: set your proxy
  headers:
    "User-Agent": "xxx" # TODO: set your user-agent
  save_dir: "./res"
  app_save_dir: "./app_res"
  backend_url: "http://127.0.0.1:8000"
  allowed_file_types: [".html",".css",".js",".png",".jpg",".jpeg",".pdf",".md"]

arxiv:
  key_word: null # keyword can be str or list of str, and can be url itself. If search daily submission, set null
  daily_type: "cs"
  download: false
  max_return: 2

openai:
  api_key: "sk-xxx" # TODO: set your api key
  prompts_path:
    './prompts_config.json'
  ignore_title: ["reference","appendix","acknowledg"]
  base_url: "https:/xxxx" # TODO: set your base url
  rpm_limit: 3 # int,  0 means no limit, >0 means the max request per miniute
  num_processes: 6
  prompt_ratio: 0.8 # prompt_len / max_tokns, 0.8 means up to 80% of max tokens can be prompt
  model_config:
    model: "gpt-3.5-turbo-16k-0613"
    temperature: 0.5
    max_tokens: 16385
    top_p: 1.0
    frequency_penalty: 0.1
    presence_penalty: 0.2

nougat:
  check_point : "./tools/nougat/pretrained_w"
  pdf : ["./data"]    # list of pdf path or pdf dir
  recompute : true
  markdown : true

tts:
  base_url: "xxx" # TODO: set your tts base url
  api_key: 'xxx' # TODO: set your tts api key
  app_secret: "xxx" # TODO: set your app secret

alignment:
  init_grid: 3  # The grid level for aligning pictures with subtitles. For example, setting it to 3 means the picture can be aligned with a 3-level subtitle (e.g., ### subtitle). Setting init_grid to 2 means it can be aligned with a 2-level subtitle (e.g., ## subtitle).
  max_grid: 4  # The maximum grid level for section splitting. For instance, setting it to 4 means the article structure can be split into 4-level subtitles (e.g., #### subtitle).
  threshold: 0.9
  img_width: 600



